// THIS FILE WAS GENERATED BY AI, DO NOT EDIT MANUALLY
use crate::bootstrap::ServiceContainer;

/// Service Provider trait
pub trait ServiceProvider: Send + Sync {
    /// Unique name for this provider
    fn name(&self) -> &str;
    
    /// Register services in the container
    fn register(&self, container: &mut ServiceContainer);
    
    /// Boot services (optional)
    fn boot(&self, _container: &ServiceContainer) {
        // Default: do nothing
    }
}

/// Provider registry
pub struct ProviderRegistry {
    providers: Vec<Box<dyn ServiceProvider>>,
}

impl ProviderRegistry {
    pub fn new() -> Self {
        Self {
            providers: Vec::new(),
        }
    }
    
    /// Add a provider
    pub fn register<P: ServiceProvider + 'static>(&mut self, provider: P) {
        self.providers.push(Box::new(provider));
    }
    
    /// Boot all providers
    pub fn boot_all(&self, container: &mut ServiceContainer) {
        // Phase 1: Register
        for provider in &self.providers {
            tracing::debug!("Registering provider: {}", provider.name());
            provider.register(container);
        }
        
        // Phase 2: Boot
        for provider in &self.providers {
            tracing::debug!("Booting provider: {}", provider.name());
            provider.boot(container);
        }
    }
}